export const REQUEST_RUN = "REQUEST_RUN"
export const RECEIVE_RUN = "RECEIVE_RUN"

export const REQUEST_INVOCATION = "REQUEST_INVOCATION"
export const RECEIVE_INVOCATION = "RECEIVE_INVOCATION"

export const REQUEST_STACKSET = "REQUEST_STACKSET"
export const RECEIVE_STACKSET = "RECEIVE_STACKSET"

export const REQUEST_FRAMES = "REQUEST_FRAMES"
export const RECEIVE_FRAMES = "RECEIVE_FRAMES"

export const REQUEST_CLASSNAMES = "REQUEST_CLASSNAMES"
export const RECEIVE_CLASSNAMES = "RECEIVE_CLASSNAMES"

export const SET_SEARCH_REQUEST = "SET_SEARCH_REQUEST"
export const SET_SEARCH_RESPONSE = "SET_SEARCH_RESPONSE"
export const REMOVE_SET_SEARCH = "REMOVE_SET_SEARCH"
export const UPDATE_SET_SEARCH = "UPDATE_SET_SEARCH"
